services:
  - type: web
    name: sentiment-analysis-api  # Replace with your desired service name
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api.predict:app --bind 0.0.0.0:10000
    autoDeploy: true
    region: oregon  # You can change this to your preferred region
