services:
  - type: web
    name: sentiment-analysis-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api.predict:app --bind 0.0.0.0:10000
    autoDeploy: true
    plan: free
